
package aaa.soap.getAutoPolicyDetails;

import aaa.soap.HTTPConfigurer;
import aaa.soap.getAutoPolicyDetails.aaancnu_wsdl_getautopolicydetail_version2.GetAutoPolicyDetail;
import org.apache.cxf.Bus;
import org.apache.cxf.bus.CXFBusFactory;
import org.apache.cxf.transport.http.HTTPConduitConfigurer;
import toolkit.config.PropertyProvider;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetAutoPolicyDetailService", targetNamespace = "http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2", wsdlLocation = "http://eqxaaawas01.eqxdev.exigengroup.com:9082/aaa-admin/services/getAutoPolicyDetail?wsdl")
public class GetAutoPolicyDetailService
    extends Service
{

    private final static URL GETAUTOPOLICYDETAILSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETAUTOPOLICYDETAILSERVICE_EXCEPTION;
    private final static QName GETAUTOPOLICYDETAILSERVICE_QNAME = new QName("http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2", "GetAutoPolicyDetailService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(String.format("http://%1$s:%2$s/aaa-admin/services/getAutoPolicyDetail?wsdl", PropertyProvider.getProperty("app.host"),PropertyProvider.getProperty("test.ws.port")));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        Bus bus = CXFBusFactory.getThreadDefaultBus();
        HTTPConduitConfigurer conf = new HTTPConfigurer("qa", "qa");
        bus.setExtension(conf, HTTPConduitConfigurer.class);
        GETAUTOPOLICYDETAILSERVICE_WSDL_LOCATION = url;
        GETAUTOPOLICYDETAILSERVICE_EXCEPTION = e;
    }

    public GetAutoPolicyDetailService() {
        super(__getWsdlLocation(), GETAUTOPOLICYDETAILSERVICE_QNAME);
    }

    public GetAutoPolicyDetailService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETAUTOPOLICYDETAILSERVICE_QNAME, features);
    }

    public GetAutoPolicyDetailService(URL wsdlLocation) {
        super(wsdlLocation, GETAUTOPOLICYDETAILSERVICE_QNAME);
    }

    public GetAutoPolicyDetailService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETAUTOPOLICYDETAILSERVICE_QNAME, features);
    }

    public GetAutoPolicyDetailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAutoPolicyDetailService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetAutoPolicyDetail
     */
    @WebEndpoint(name = "GetAutoPolicyDetailSOAPPort")
    public GetAutoPolicyDetail getGetAutoPolicyDetailSOAPPort() {
        return super.getPort(new QName("http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2", "GetAutoPolicyDetailSOAPPort"), GetAutoPolicyDetail.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAutoPolicyDetail
     */
    @WebEndpoint(name = "GetAutoPolicyDetailSOAPPort")
    public GetAutoPolicyDetail getGetAutoPolicyDetailSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2", "GetAutoPolicyDetailSOAPPort"), GetAutoPolicyDetail.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETAUTOPOLICYDETAILSERVICE_EXCEPTION!= null) {
            throw GETAUTOPOLICYDETAILSERVICE_EXCEPTION;
        }
        return GETAUTOPOLICYDETAILSERVICE_WSDL_LOCATION;
    }

}
