
package aaa.soap.aaaCSPolicyRate.exigenservices;

import aaa.soap.aaaCSPolicyRate.RatePolicyRequest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CSPolicyRatePort", targetNamespace = "http://exigenservices.com/ipb/policy/integration")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    aaa.soap.aaaCSPolicyRate.aaancnu_common_version2.ObjectFactory.class,
    aaa.soap.aaaCSPolicyRate.exigeninsurance.eis.ObjectFactory.class,
    aaa.soap.aaaCSPolicyRate.exigeninsurance.eis.product.ObjectFactory.class,
    ObjectFactory.class,
    aaa.soap.aaaCSPolicyRate.exigeninsurance.aaa_csa_lookup.ObjectFactory.class,
    aaa.soap.aaaCSPolicyRate.exigeninsurance.aaa_csa_db.ObjectFactory.class
})
public interface CSPolicyRatePort {


    /**
     * 
     * @param request
     * @return
     *     returns com.exigenservices.ipb.policy.integration.RatePolicyRequest
     * @throws ErrorInfo
     */
    @WebMethod(operationName = "RateQuote", action = "http://exigenservices.com/ipb/policy/integration/RateQuote")

    @WebResult(name = "RatePolicyRequest", targetNamespace = "http://exigenservices.com/ipb/policy/integration", partName = "response")
    public RatePolicyRequest rateQuote(
        @WebParam(name = "RatePolicyRequest", targetNamespace = "http://exigenservices.com/ipb/policy/integration", partName = "request")
        RatePolicyRequest request)
        throws ErrorInfo
    ;

}
