
package aaa.soap.aaaCSPolicyRate.exigenservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ErrorInfo", targetNamespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")
public class ErrorInfo
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private aaa.soap.aaaCSPolicyRate.aaancnu_common_version2.ErrorInfo faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ErrorInfo(String message, aaa.soap.aaaCSPolicyRate.aaancnu_common_version2.ErrorInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ErrorInfo(String message, aaa.soap.aaaCSPolicyRate.aaancnu_common_version2.ErrorInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: aaancnu_common_version2.com.aaancnuit.ErrorInfo
     */
    public aaa.soap.aaaCSPolicyRate.aaancnu_common_version2.ErrorInfo getFaultInfo() {
        return faultInfo;
    }

}
