package aaa.soap.aaaCSPolicyRate.com.exigenservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-16T20:33:48.509-07:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://exigenservices.com/ipb/policy/integration", name = "CSPolicyRatePort")
@XmlSeeAlso({aaa.soap.aaaCSPolicyRate.com.exigeninsurance.data.aaa_csa_db.ObjectFactory .class, ObjectFactory.class, aaa.soap.aaaCSPolicyRate.com.exigeninsurance.data.eis.ObjectFactory.class, aaa.soap.aaaCSPolicyRate.com.exigeninsurance.eis.schema.ObjectFactory.class, aaa.soap.aaaCSPolicyRate.aaancnu_common_version2.ObjectFactory.class, aaa.soap.aaaCSPolicyRate.com.exigeninsurance.data.aaa_csa_lookup.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CSPolicyRatePort {

    @WebMethod(operationName = "RateQuote", action = "http://exigenservices.com/ipb/policy/integration/RateQuote")
    @WebResult(name = "RatePolicyRequest", targetNamespace = "http://exigenservices.com/ipb/policy/integration", partName = "response")
    public RatePolicyRequest rateQuote(
		    @WebParam(partName = "request", name = "RatePolicyRequest", targetNamespace = "http://exigenservices.com/ipb/policy/integration")
				    RatePolicyRequest request
    ) throws ErrorInfo;
}
