
package aaa.soap.autopolicy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.*;
import org.apache.cxf.Bus;
import org.apache.cxf.BusFactory;
import org.apache.cxf.transport.http.HTTPConduitConfigurer;
import com.exigen.ipb.eisa.base.app.CSAAApplicationFactory;
import aaa.soap.AAAHTTPConfigurer;
import aaa.soap.autopolicy.models.wsdl.GetAutoPolicyDetail;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetAutoPolicyDetailService", targetNamespace = "http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2", wsdlLocation = "http://eqxaaawas01.eqxdev.exigengroup.com:9082/aaa-admin/services/getAutoPolicyDetail?wsdl")
public class GetAutoPolicyDetailService
    extends Service
{

    private static final URL GETAUTOPOLICYDETAILSERVICE_WSDL_LOCATION;
    private static final WebServiceException GETAUTOPOLICYDETAILSERVICE_EXCEPTION;
    private static final QName GETAUTOPOLICYDETAILSERVICE_QNAME = new QName("http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2", "GetAutoPolicyDetailService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(CSAAApplicationFactory.get().adminApp().getUrl().replace("/admin", "").concat("/services/getAutoPolicyDetail?wsdl"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        Bus bus = BusFactory.getThreadDefaultBus();
        HTTPConduitConfigurer conf = new AAAHTTPConfigurer("qa", "qa");
        bus.setExtension(conf, HTTPConduitConfigurer.class);
        GETAUTOPOLICYDETAILSERVICE_WSDL_LOCATION = url;
        GETAUTOPOLICYDETAILSERVICE_EXCEPTION = e;
    }

    public GetAutoPolicyDetailService() {
        super(__getWsdlLocation(), GETAUTOPOLICYDETAILSERVICE_QNAME);
    }

    public GetAutoPolicyDetailService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETAUTOPOLICYDETAILSERVICE_QNAME, features);
    }

    public GetAutoPolicyDetailService(URL wsdlLocation) {
        super(wsdlLocation, GETAUTOPOLICYDETAILSERVICE_QNAME);
    }

    public GetAutoPolicyDetailService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETAUTOPOLICYDETAILSERVICE_QNAME, features);
    }

    public GetAutoPolicyDetailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAutoPolicyDetailService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetAutoPolicyDetail
     */
    @WebEndpoint(name = "GetAutoPolicyDetailSOAPPort")
    public GetAutoPolicyDetail getGetAutoPolicyDetailSOAPPort() {
        return getPort(new QName("http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2", "GetAutoPolicyDetailSOAPPort"), GetAutoPolicyDetail.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAutoPolicyDetail
     */
    @WebEndpoint(name = "GetAutoPolicyDetailSOAPPort")
    public GetAutoPolicyDetail getGetAutoPolicyDetailSOAPPort(WebServiceFeature... features) {
        return getPort(new QName("http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2", "GetAutoPolicyDetailSOAPPort"), GetAutoPolicyDetail.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETAUTOPOLICYDETAILSERVICE_EXCEPTION!= null) {
            throw GETAUTOPOLICYDETAILSERVICE_EXCEPTION;
        }
        return GETAUTOPOLICYDETAILSERVICE_WSDL_LOCATION;
    }

}
