
package aaa.soap.aaaSSPolicyRate.version1_6.com.exigenservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-17T13:33:37.998-07:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "ErrorInfo", targetNamespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")
public class ErrorInfo extends Exception {
//aaancnu_common_version2.com.aaancnuit.
    private ErrorInfo errorInfo;

    public ErrorInfo() {
        super();
    }

    public ErrorInfo(String message) {
        super(message);
    }

    public ErrorInfo(String message, Throwable cause) {
        super(message, cause);
    }

    public ErrorInfo(String message, ErrorInfo errorInfo) {
        super(message);
        this.errorInfo = errorInfo;
    }

    public ErrorInfo(String message, ErrorInfo errorInfo, Throwable cause) {
        super(message, cause);
        this.errorInfo = errorInfo;
    }

    public ErrorInfo getFaultInfo() {
        return this.errorInfo;
    }
}
