package aaa.soap.aaaSSPolicyRate.version1_6.com.exigenservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-17T13:33:38.047-07:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://exigenservices.com/ipb/policy/integration", name = "SSPolicyRatePort")
@XmlSeeAlso({aaa.soap.aaaSSPolicyRate.version1_6.com.exigeninsurance.schema.ObjectFactory.class, ObjectFactory.class, aaa.soap.aaaSSPolicyRate.version1_6.com.exigeninsurance.data.aaa_ss_lookup.ObjectFactory.class, aaa.soap.aaaSSPolicyRate.version1_6.com.exigeninsurance.data.eis.ObjectFactory .class, aaa.soap.aaaSSPolicyRate.version1_6.aaancnu_common_version2.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SSPolicyRatePort {

    @WebMethod(operationName = "RateQuote", action = "http://exigenservices.com/ipb/policy/integration/RateQuote")
    @WebResult(name = "RatePolicyRequest", targetNamespace = "http://exigenservices.com/ipb/policy/integration", partName = "response")
    public RatePolicyRequest rateQuote(
		    @WebParam(partName = "request", name = "RatePolicyRequest", targetNamespace = "http://exigenservices.com/ipb/policy/integration")
				    RatePolicyRequest request
    ) throws ErrorInfo;
}
