
package aaa.soap.getAutoPolicyDetails.aaancnu_wsdl_getautopolicydetail_version2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetAutoPolicyDetail", targetNamespace = "http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    aaa.soap.getAutoPolicyDetails.aaancnu_common_version2.ObjectFactory.class,
    aaa.soap.getAutoPolicyDetails.aaancnu_getautopolicydetail_version2.ObjectFactory.class,
    aaa.soap.getAutoPolicyDetails.aaancnu_wsdl_getautopolicydetail_version2.ObjectFactory.class
})
public interface GetAutoPolicyDetail {


    /**
     * 
     * @param getAutoPolicyDetail
     * @return
     *     returns aaa.soap.getAutoPolicyDetails.aaancnu_wsdl_getautopolicydetail_version2;.GetAutoPolicyDetailResponse
     * @throws ErrorInfo
     */
    @WebMethod(operationName = "GetAutoPolicyDetail", action = "http://www.aaancnuit.com.getAutoPolicyDetail")
    @WebResult(name = "getAutoPolicyDetailResponse", targetNamespace = "http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2", partName = "getAutoPolicyDetail")
    public GetAutoPolicyDetailResponse getAutoPolicyDetail(
        @WebParam(name = "getAutoPolicyDetailRequest", targetNamespace = "http://www.aaancnuit.com.AAANCNU_WSDL_GetAutoPolicyDetail_version2", partName = "getAutoPolicyDetail")
        GetAutoPolicyDetailRequest getAutoPolicyDetail)
        throws ErrorInfo
    ;

}
