package aaa.modules.regression.queries;

public interface MsrpQueries {
	String UPDATE_MSRP_COMP_COLL_CONTROL_VERSION_VEHICLEYEARMAX = "UPDATE MSRPCompCollCONTROL SET VEHICLEYEARMAX = %1$d WHERE MSRPVERSION = '%2$s'";
	String UPDATE_MSRP_COMP_COLL_CONTROL_VERSION_VEHICLEYEARMAX_BY_KEY_VEHICLEYEARMIN = "UPDATE MSRPCompCollCONTROL SET VEHICLEYEARMAX = %1$d WHERE VEHICLEYEARMIN = %2$d AND KEY = %3$d";

	String INSERT_VERSION_INTO_MSRP_COMP_COLL_CONTROL = "insert into MsrpCompCollControl(vehicleyearmin, vehicleyearmax, vehicletype, liabilitysymbol, msrpversion, key)"
			+ "values(%1$d,%2$d,'%3$s',null,'%4$s',%5$d)";
	String UPDATE_VEHICLEREFDATAVINCONTROL_EXPIRATIONDATE_BY_STATECD_MSRPVERSION = "UPDATE vehiclerefdatavincontrol SET expirationdate='%1$d' WHERE STATECD='%2$s' AND MSRP_VERSION='%3$s'";
	String UPDATE_VEHICLEREFDATAVINCONTROL_EXPIRATIONDATE_BY_STATECD_MSRPVERSION_FORMTYPE = "UPDATE vehiclerefdatavincontrol SET expirationdate='%1$d' WHERE STATECD='%2$s' AND MSRP_VERSION='%3$s' AND FORMTYPE = '%4$s'";
	String SELECT_VEHICLEREFDATAVINCONTROL_MAX_ID = "SELECT MAX(id) FROM VEHICLEREFDATAVINCONTROL";

	String INSERT_MSRPCOMPCOLLCONTROL_VERSION = "insert into MsrpCompCollControl(vehicleyearmin, vehicleyearmax, vehicletype, liabilitysymbol, msrpversion, key) values "
			+ "(%1$d,%2$d,'%3$s',null,'%4$s',%5$d)";

	String DELETE_FROM_MSRPCompCollCONTROL_BY_VERSION_KEY = "DELETE from MSRPCompCollCONTROL WHERE MSRPVERSION = '%1$s' AND KEY = %2$d AND VEHICLETYPE = '%3$s'";
	String DELETE_FROM_VEHICLEREFDATAVINCONTROL_BY_VERSION_STATECD = "DELETE FROM VEHICLEREFDATAVINCONTROL WHERE MSRP_VERSION = '%1$s' AND STATECD = '%2$s'";

	String NEWLY_ADDED_MSRP_VERSION_FOR_PPA_VEH_AUTO_SS = "MSRP_2000_SS";
	String NEWLY_ADDED_MSRP_VERSION_FOR_MOTORHOME_VEH_AUTO_SS = "MSRP_2000_MOTORHOME_SS";

	String NEWLY_ADDED_MSRP_VERSION_FOR_REGULAR_VEH_AUTO_CA_CHOICE = "MSRP_2000_CHOICE_TEST";
	String NEWLY_ADDED_MSRP_VERSION_FOR_MOTORHOME_VEH_AUTO_CA_CHOICE = "MSRP_2000_MOTORHOME_CHOICE_TEST";

	String NEWLY_ADDED_MSRP_VERSION_FOR_REGULAR_VEH_AUTO_CA_SELECT = "MSRP_2000_SELECT_TEST";
	String NEWLY_ADDED_MSRP_VERSION_FOR_MOTORHOME_VEH_AUTO_CA_SELECT = "MSRP_2000_MOTORHOME_SELECT_TEST";


}
